services:
  ollama:
    image: 'ollama/ollama:latest'
    container_name: ollama
    ports:
      - '11434:11434'
    volumes:
      - ollama:/root/.ollama
#    command: ollama run mistral
    networks:
      - DHA
  pgvector:
    image: 'pgvector/pgvector:pg16'
    environment:
      POSTGRES_DB: vector_store
      POSTGRES_PASSWORD: comrade
      POSTGRES_USER: dear
      VECTOR_STORE_TYPE: pgVector
    labels:
      - "org.springframework.boot.service-connection=postgres"
    ports:
      - '5432'
    networks:
      - DHA
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
    volumes:
      - ./servers.json:/pgadmin4/servers.json
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - DHA
networks:
  DHA:
    driver: bridge
volumes:
  ollama: {}