server:
  port: 8084
  shutdown: GRACEFUL

spring:
  application:
    name: ollama-llama3
  ai:
    ollama:
      base-url: http://localhost:11434/
      embedding:
        enabled: true
        model: llava
        options:
          model: llava
      chat:
        enabled: true
        model: llava
        options:
          model: llava

springdoc:
  swagger-ui:
    path: /swagger-ui.html

pdf:
  path: classpath:Shiva_Java_Developer.pdf

image:
  height: 1024
  width: 1024
  order: 1
  format: url #openai - url or base64 : stability ai byte[] or base64

