server:
  port: 8084
spring:
  ai:
    vectorstore:
      pgvector:
        index-type: none #ivfflat
        distance-type: COSINE_DISTANCE
        dimensions: 4096
        initialize-schema: false
        schema-validation: false
        remove-existing-vector-store-table: false
    ollama:
      baseUrl: http://localhost:11434/
      chat:
        options:
          model: mistral
      embedding:
        options:
          model: mistral

  datasource:
    url: jdbc:postgresql://localhost/vector_store
    username: dear
    password: comrade
    hikari:
      connection-timeout: 2000
      maximum-pool-size: 5
      auto-commit: false

  jpa:
    show-sql: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html

pdf:
  path: classpath:medicaid-wa-faqs.pdf
resume:
  path: classpath:shiva_java_developer.pdf
